import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "VS Code for AI Engineers" topic (docs instance id: vscode).
const sidebars: SidebarsConfig = {
  vscodeSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
