import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "Business Intelligence" topic (docs instance id: business-intelligence).
const sidebars: SidebarsConfig = {
  biSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
