import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "Genie & Business Intelligence" topic (docs instance id: genie).
const sidebars: SidebarsConfig = {
  genieSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
