import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "Agentic Coding" topic (docs instance id: agentic-coding).
// Subtopics (VS Code, Claude Code) are subfolders and render as categories.
const sidebars: SidebarsConfig = {
  agenticCodingSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
