import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "DAIS 2026" topic (docs instance id: dais-2026).
// The intro is the high-level overview; each announcement is its own page.
const sidebars: SidebarsConfig = {
  dais2026Sidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
