import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the "Databricks Features" topic (docs instance id: databricks-features).
// Each feature is a top-level page; the index (intro) is pinned first.
const sidebars: SidebarsConfig = {
  databricksFeaturesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
